# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/visionai/v1/lva_resources.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import field_behavior_pb2 as google_dot_api_dot_field__behavior__pb2
from google.api import resource_pb2 as google_dot_api_dot_resource__pb2
from useful_lva_sdk.common import lva_pb2 as google_dot_cloud_dot_visionai_dot_v1_dot_lva__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,google/cloud/visionai/v1/lva_resources.proto\x12\x18google.cloud.visionai.v1\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\x1a\"google/cloud/visionai/v1/lva.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x85\x06\n\x08\x41nalysis\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x34\n\x0b\x63reate_time\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.TimestampB\x03\xe0\x41\x03\x12\x34\n\x0bupdate_time\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.TimestampB\x03\xe0\x41\x03\x12>\n\x06labels\x18\x04 \x03(\x0b\x32..google.cloud.visionai.v1.Analysis.LabelsEntry\x12I\n\x13\x61nalysis_definition\x18\x05 \x01(\x0b\x32,.google.cloud.visionai.v1.AnalysisDefinition\x12Z\n\x15input_streams_mapping\x18\x06 \x03(\x0b\x32;.google.cloud.visionai.v1.Analysis.InputStreamsMappingEntry\x12\\\n\x16output_streams_mapping\x18\x07 \x03(\x0b\x32<.google.cloud.visionai.v1.Analysis.OutputStreamsMappingEntry\x12\x1b\n\x13\x64isable_event_watch\x18\x08 \x01(\x08\x1a-\n\x0bLabelsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a:\n\x18InputStreamsMappingEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a;\n\x19OutputStreamsMappingEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01:u\xea\x41r\n visionai.googleapis.com/Analysis\x12Nprojects/{project}/locations/{location}/clusters/{cluster}/analyses/{analysis}B\xc1\x01\n\x1c\x63om.google.cloud.visionai.v1B\x11LvaResourcesProtoP\x01Z8cloud.google.com/go/visionai/apiv1/visionaipb;visionaipb\xaa\x02\x18Google.Cloud.VisionAI.V1\xca\x02\x18Google\\Cloud\\VisionAI\\V1\xea\x02\x1bGoogle::Cloud::VisionAI::V1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'google.cloud.visionai.v1.lva_resources_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\034com.google.cloud.visionai.v1B\021LvaResourcesProtoP\001Z8cloud.google.com/go/visionai/apiv1/visionaipb;visionaipb\252\002\030Google.Cloud.VisionAI.V1\312\002\030Google\\Cloud\\VisionAI\\V1\352\002\033Google::Cloud::VisionAI::V1'
  _ANALYSIS_LABELSENTRY._options = None
  _ANALYSIS_LABELSENTRY._serialized_options = b'8\001'
  _ANALYSIS_INPUTSTREAMSMAPPINGENTRY._options = None
  _ANALYSIS_INPUTSTREAMSMAPPINGENTRY._serialized_options = b'8\001'
  _ANALYSIS_OUTPUTSTREAMSMAPPINGENTRY._options = None
  _ANALYSIS_OUTPUTSTREAMSMAPPINGENTRY._serialized_options = b'8\001'
  _ANALYSIS.fields_by_name['create_time']._options = None
  _ANALYSIS.fields_by_name['create_time']._serialized_options = b'\340A\003'
  _ANALYSIS.fields_by_name['update_time']._options = None
  _ANALYSIS.fields_by_name['update_time']._serialized_options = b'\340A\003'
  _ANALYSIS._options = None
  _ANALYSIS._serialized_options = b'\352Ar\n visionai.googleapis.com/Analysis\022Nprojects/{project}/locations/{location}/clusters/{cluster}/analyses/{analysis}'
  _ANALYSIS._serialized_start=204
  _ANALYSIS._serialized_end=977
  _ANALYSIS_LABELSENTRY._serialized_start=692
  _ANALYSIS_LABELSENTRY._serialized_end=737
  _ANALYSIS_INPUTSTREAMSMAPPINGENTRY._serialized_start=739
  _ANALYSIS_INPUTSTREAMSMAPPINGENTRY._serialized_end=797
  _ANALYSIS_OUTPUTSTREAMSMAPPINGENTRY._serialized_start=799
  _ANALYSIS_OUTPUTSTREAMSMAPPINGENTRY._serialized_end=858
# @@protoc_insertion_point(module_scope)
